### ISSUE TITLE
Date picker not showing today and tomorrow day.

### ISSUE THREAD

**Issue by nasirlordno1** [florent37/SingleDateAndTimePicker#264] opened 2020-03-19 10:03 UTC
Datepicker isnt showing today and tomorrrow date. and previous date dayname is also wrong. 
today date is 19 Mar.

![date-picker](https://user-images.githubusercontent.com/54404588/77055475-c23cfb80-69f2-11ea-957e-f8da6aa76a5b.jpg)

**Comment by fawadaliii** [comment] 2020-03-21 12:11
i got same problem whats the issue is this?

**Comment by parkarta** [comment] 2020-03-26 09:59
Yes this is the issue appearing my side too.. please help.

**Comment by fawadaliii** [comment] 2020-03-26 11:36
@parkarta I also didn't find any solution till now.

**Comment by fawadaliii** [comment] 2020-03-26 11:36
where is @nasirlordno1 any guide??

**Comment by nasirlordno1** [comment] 2020-03-26 14:15
> where is @nasirlordno1 any guide??

no solution.I am also waiting for someone to answer.

**Comment by jturin** [comment] 2020-03-27 12:59
Looks like the library is not prepared for leap years:
[https://github.com/florent37/SingleDateAndTimePicker/blob/master/singledateandtimepicker/src/main/java/com/github/florent37/singledateandtimepicker/widget/SingleDateAndTimeConstants.java#L9](url)

**Comment by ardevd** [comment] 2020-04-01 20:41
Same issue here. Any way to resolve the issue?

**Comment by ardevd** [comment] 2020-04-01 20:45
Downgrading to v2.1.4 fixes the issue for me.

**Comment by G00fY2** [comment] 2020-04-03 10:34
Issue appears since 2.1.6. I am currently investigating and trying to provide a PR.

**Comment by arberg** [comment] 2020-04-05 12:06
This issue can be closed now. Fixed in v2.2.1.

**Closed** 2020-04-05 16:35 UTC
